### ISSUE TITLE
Reader with custom blocks and stylings

### ISSUE THREAD

**Issue by Hellycat** [roast-cms/french-press-editor#112]
Thank you for good package!
This package is used as a Render for production build (editor writing in Slate.js). From slate.js issues I got know about you package, that it could be used for read-only mode.

It works fine in general. I just can't find how to pass function to render customs blocks (in my case it image) and how to style default one like <p>, <a> etc (for example it would be great to support set custom styles).

Maybe I miss smth in docs. I know that there is a components={{ Picture }} props but in some case it doesn't work.

Does it possible to do it? Maybe I could extend default behavior for this case, what do you thin about it?

**Comment by dmitrizzle** [comment]
You can style default image block via Styled Components or with CSS. What do you mean by `in some case it doesn't work.` - can you give me a way to replicate the issue?

**Comment by dmitrizzle** [comment]
Hey @Hellycat I don't think I understand what you mean by the feature you're proposing. Feel free to make a PR (I'll probably see better from the code what you hoping to do) or try to explain a little further.

Thank you for your support and interest!
